### ISSUE TITLE
Does not work on Windows

### ISSUE THREAD

**Issue by mydea** [simonihmig/ember-test-helpers-codemod#11]
On Windows, I get the following error message after installing it with `yarn global add ember-test-helpers-codemod`:

```
$ ember-test-helpers-codemod --type=integration tests/integration
Error: spawn UNKNOWN
    at _errnoException (util.js:1026:11)
    at ChildProcess.spawn (internal/child_process.js:325:11)
    at exports.spawn (child_process.js:493:9)
    at Object.<anonymous> (C:\Users\roaster\AppData\Local\Yarn\config\global\node_modules\ember-test-helpers-codemod\bin\ember-test-helpers-codemod.js:12:3)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
    at Function.Module.runMain (module.js:665:10)
```

I tried playing around a bit, but could not really figure out what the problem is. Let me know if there is anything I can do to help!

**Comment by simonihmig** [comment]
Hm, thanks for reporting! 

This could be the root issue: https://stackoverflow.com/questions/43419893/how-do-i-fix-error-spawn-unknown-with-node-js-v7-8-0-on-windows-10, which throws here: https://github.com/simonihmig/ember-test-helpers-codemod/blob/master/bin/ember-test-helpers-codemod.js#L12

As a workaround for now, you could run `jscodeshift` directly, like `jscodeshift -t path/to/lib/presets/acceptance.js tests`.

`ember-modules-codemod` uses `execa` instead of `spawn` [here](https://github.com/ember-cli/ember-modules-codemod/blob/master/bin/ember-modules-codemod.js#L25), which seems to have better Windows and shebang support: https://github.com/sindresorhus/execa. Replacing this would hopefully fix the issue.

Unfortunately, I have no easy access to a ready to use Windows environment, so a PR would certainly be welcome! 😉
