### ISSUE TITLE
Failure when encountering `andThen(() => { click('...') })`

### ISSUE THREAD

**Issue by jgwhite** [simonihmig/ember-test-helpers-codemod#22]
### What I did

```sh
$ ember-test-helpers-codemod --type=acceptance example-test.js
```

Where `example-test.js` contains:

```js
test('example', function() {
  andThen(() => {
    click('.some-button');
  });
});
```

### What I expected to happen

```
0 errors
0 unmodified
0 skipped
1 ok
```

### What actually happened

```
Processing 1 files...
Spawning 1 workers...
Sending 1 files to free worker...
 ERR /Users/jameswhite/Desktop/example-test.js Transformation error
Error: Transformation visit.js errored on file /Users/jameswhite/Desktop/example-test.js. Reason SyntaxError: Unexpected token (3:8). Please report this in https://github.com/simonihmig/ember-test-helpers-codemod/issues

Stack trace:
SyntaxError: Unexpected token (3:8)
    at Parser.pp.raise (/Users/jameswhite/.config/yarn/global/node_modules/ember-test-helpers-codemod/node_modules/babel-core/node_modules/babylon/lib/parser/location.js:24:13)
    at Parser.pp.unexpected (/Users/jameswhite/.config/yarn/global/node_modules/ember-test-helpers-codemod/node_modules/babel-core/node_modules/babylon/lib/parser/util.js:82:8)
    at Parser.pp.semicolon (/Users/jameswhite/.config/yarn/global/node_modules/ember-test-helpers-codemod/node_modules/babel-core/node_modules/babylon/lib/parser/util.js:69:81)
    at Parser.pp.parseExpressionStatement (/Users/jameswhite/.config/yarn/global/node_modules/ember-test-helpers-codemod/node_modules/babel-core/node_modules/babylon/lib/parser/statement.js:427:8)
    at Parser.parseExpressionStatement (/Users/jameswhite/.config/yarn/global/node_modules/ember-test-helpers-codemod/node_modules/babel-core/node_modules/babylon/lib/plugins/flow.js:676:20)
    at Parser.pp.parseStatement (/Users/jameswhite/.config/yarn/global/node_modules/ember-test-helpers-codemod/node_modules/babel-core/node_modules/babylon/lib/parser/statement.js:142:21)
    at Parser.parseStatement (/Users/jameswhite/.config/yarn/global/node_modules/ember-test-helpers-codemod/node_modules/babel-core/node_modules/babylon/lib/plugins/flow.js:655:22)
    at Parser.pp.parseBlock (/Users/jameswhite/.config/yarn/global/node_modules/ember-test-helpers-codemod/node_modules/babel-core/node_modules/babylon/lib/parser/statement.js:442:21)
    at Parser.pp.parseFunctionBody (/Users/jameswhite/.config/yarn/global/node_modules/ember-test-helpers-codemod/node_modules/babel-core/node_modules/babylon/lib/parser/expression.js:747:22)
    at Parser.parseFunctionBody (/Users/jameswhite/.config/yarn/global/node_modules/ember-test-helpers-codemod/node_modules/babel-core/node_modules/babylon/lib/plugins/flow.js:643:20)

Source:
import { click } from '@ember/test-helpers';
test('example', function() {
  await click('.some-button');
});

    at fs.readdirSync.forEach.fileName (/Users/jameswhite/.config/yarn/global/node_modules/ember-test-helpers-codemod/lib/presets/-preset.js:23:19)
    at Array.forEach (<anonymous>)
    at /Users/jameswhite/.config/yarn/global/node_modules/ember-test-helpers-codemod/lib/presets/-preset.js:15:8
    at module.exports (/Users/jameswhite/.config/yarn/global/node_modules/ember-test-helpers-codemod/index.js:15:14)
All done.
Results:
1 errors
0 unmodified
0 skipped
0 ok
Time elapsed: 0.623seconds
```

**Comment by simonihmig** [comment]
Thanks for reporting!

I guess the `click` transform makes the `andThen` callback an `async` function, which is later dropped when removing the `andThen()`. So we end up with what you see in the logs, an `await` without `async`...

I would still expect this test to be written as 
```js
andThen(() => {
  // some assertions    
});
click('.some-button');
```

But nevertheless it should certainly be able to cope with that...
