### ISSUE TITLE
"path argument is required" error when running this codemod

### ISSUE THREAD

**Issue by tomwayson** [simonihmig/ember-test-helpers-codemod#32]
I'm running this codemod as part of `ember-cli-update` and I get the following error:

```bash
➜  ember-arcgis-server-services git:(chore/ember-3-5) ember-cli-update --run-codemods
? These codemods apply to your project. Select which ones to run. ember-test-h
elpers-codemod
npx: installed 383 in 9.299s

path argument is required

Usage: jscodeshift <path>... [options]

path     Files or directory to transform
```

Then it shows below:

```bash
Error: Command failed: /Users/tom/.npm/_npx/70046/lib/node_modules/ember-test-helpers-codemod/node_modules/jscodeshift/bin/jscodeshift.sh -t /Users/tom/.npm/_npx/70046/lib/node_modules/ember-test-helpers-codemod/transforms/integration/index.js --extensions js,ts
    at makeError (/Users/tom/.npm/_npx/70046/lib/node_modules/ember-test-helpers-codemod/node_modules/execa/index.js:172:9)
    at Promise.all.then.arr (/Users/tom/.npm/_npx/70046/lib/node_modules/ember-test-helpers-codemod/node_modules/execa/index.js:277:16)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

I'm upgrading my addon from 2.18 to 3.5 in steps for each minor (2.18 -> 3.0 -> 3.1 -> ...) and the above message is from after upgrading to 3.3, but I have seen the same message at each step that I've run this codemod on.

**Comment by rinoldsimon** [comment]
getting the same issue when upgrading from 3.4.3 to 3.5

**Comment by rwjblue** [comment]
Ya, seems good to me.

**Comment by kellyselden** [comment]
Does it make sense to infer all the options and instead run `ember-test-helpers-codemod` only?

**Comment by xtagon** [comment]
When I encountered this error, adding an empty `tests/acceptance` directory wasn't enough to fix it, but generating a new acceptance test did. Just sharing that in case anyone is in a similar situation
